### ISSUE TITLE
Unpacking error: error('unpack requires a buffer of 4 bytes',)

### ISSUE THREAD

**Issue by JianYugen** [deparkes/OOMMFTools#23]
Hi. I've met an issue recently when using OOMMFDecode to convert .ovf files into MATLAB data files. The program runs correctly for vector files in most cases. But when it comes to some scalar files, there arise error message as below:
```
Data indicator: # Begin: Data Binary 4
Little-endian 4-byte detected.
unpack requires a buffer of 4 bytes
Traceback (most recent call last):
  File "D:\OOMMFTools\oommftools\user_interfaces\gui\oommfdecode.py", line 216, in OnDropFiles
    maximum=len(oommf)))
  File "D:\OOMMFTools\oommftools\user_interfaces\gui\oommfdecode.py", line 243, in groupUnpack
    return (decodedArrays, headers, extraData)
UnboundLocalError: local variable 'decodedArrays' referenced before assignment
```
![error](https://user-images.githubusercontent.com/81697579/132851754-9a594ecc-801c-490f-8e43-3a64110cdf49.png)

In OOMMF, the relevant quantities of scalar files are saved in the X coordinate, so they are still vectors in fact. Actually I can check scalar files through other ways, and I'm just wondering what goes wrong. Thanks.

**Comment by deparkes** [comment]
Hi, Would you be able to share an example of a file that causes this error?

**Comment by JianYugen** [comment]
There's a file output by mumax3 ([mumax3 is a GPU-accelerated micromagnetic simulation program](http://mumax.github.io/index.html)). It saved the temperature distribution of the system, where I defined a thermal gradient (300-500K) along the X direction. Fig.1 shows what it views in OOMMF. Fig.2 is the bitmap file converted by OOMMFConvert.

[example.zip](https://github.com/deparkes/OOMMFTools/files/7267127/example.zip)

**Comment by deparkes** [comment]
Thanks, I can recreate the error now. I'll see if I can find and fix the problem, but I'm glad you're able to check the scalar files in other ways in case I can't fix it!

**Comment by JianYugen** [comment]
Good luck! MATLAB data files would be always easier for me to analyse.
